apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crud
  labels:
    app: go-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-crud
  template:
    metadata:
      labels:
        app: go-crud
    spec:
      containers:
        - name: go-crud
          image: shreyaseth26/go-crud
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: DB_URL
              value: "host=pg-67079ff-go-crud.l.aivencloud.com user=avnadmin password=AVNS_SXLgo_hkok2GWW7HXnE dbname=defaultdb port=16553 sslmode=require"
